import { describe, it } from 'node:test'
import assert from 'node:assert/strict'
import fs from 'node:fs'
import path from 'node:path'
import { parse } from '../parser.js'
import { validate } from '../validator.js'
import { generateKoaCode } from './koa.js'

const SNAPSHOT_DIR = path.resolve(process.cwd(), 'src/codegen/__snapshots__/koa')
const EXAMPLES_DIR = path.resolve(process.cwd(), 'examples')

const UPDATE_SNAPSHOTS = process.env.UPDATE_SNAPSHOTS === '1'

function loadSnapshot(name: string): string | null {
  const filePath = path.join(SNAPSHOT_DIR, `${name}.snap`)
  try { return fs.readFileSync(filePath, 'utf-8') } catch { return null }
}

function saveSnapshot(name: string, code: string): void {
  if (!fs.existsSync(SNAPSHOT_DIR)) fs.mkdirSync(SNAPSHOT_DIR, { recursive: true })
  fs.writeFileSync(path.join(SNAPSHOT_DIR, `${name}.snap`), code, 'utf-8')
}

const exampleFiles = fs.readdirSync(EXAMPLES_DIR)
  .filter(f => f.endsWith('.clear'))
  .sort()

for (const exampleFile of exampleFiles) {
  const snapshotName = exampleFile.replace(/\.clear$/, '')
  const filePath = path.join(EXAMPLES_DIR, exampleFile)
  const source = fs.readFileSync(filePath, 'utf-8')
  const parseResult = parse(source, exampleFile)
  const ast = parseResult.ast

  describe(`Koa codegen: ${exampleFile}`, () => {
    it('should parse successfully', () => {
      assert.ok(ast !== null, `Parse failed: ${parseResult.errors.map(e => `${e.message} (${e.span.start.line}:${e.span.start.col})`).join('; ')}`)
    })
    if (ast === null) return

    const productName = ast.product.name

    it('should validate successfully', () => {
      const validation = validate(ast)
      const errMsgs = validation.errors.map(e => `  ${e.message} (${e.span.start.line}:${e.span.start.col})`)
      assert.ok(validation.valid, `Validation failed:\n${errMsgs.join('\n')}`)
    })

    const validation = validate(ast)
    const generatedCode = validation.valid ? generateKoaCode(ast) : ''
    if (!validation.valid || !generatedCode) return

    it('should match stored snapshot', () => {
      if (UPDATE_SNAPSHOTS) { saveSnapshot(snapshotName, generatedCode); return }
      const existing = loadSnapshot(snapshotName)
      if (existing === null) { saveSnapshot(snapshotName, generatedCode); return }
      assert.strictEqual(generatedCode, existing)
    })

    it('should include auto-generated header', () => {
      assert.ok(generatedCode.includes('Auto-generated by Clear'))
      assert.ok(generatedCode.includes('Do not edit'))
      assert.ok(generatedCode.includes(`Source: ${productName}`))
    })

    it('should import from koa, @koa/router, @koa/cors, and @koa/bodyparser', () => {
      assert.ok(generatedCode.includes("import Koa from 'koa'"))
      assert.ok(generatedCode.includes("import Router from '@koa/router'"))
      assert.ok(generatedCode.includes("import cors from '@koa/cors'"))
      assert.ok(generatedCode.includes("import { bodyParser } from '@koa/bodyparser'"))
    })

    it('should export default app', () => {
      assert.ok(generatedCode.includes('export default app'))
    })

    it('should set up Koa app with cors, bodyParser, and router', () => {
      assert.ok(generatedCode.includes('const app = new Koa()'))
      assert.ok(generatedCode.includes('const router = new Router()'))
      assert.ok(generatedCode.includes('app.use(cors())'))
      assert.ok(generatedCode.includes('app.use(bodyParser())'))
      assert.ok(generatedCode.includes('app.use(router.routes()).use(router.allowedMethods())'))
    })

    it('should listen on a port', () => {
      assert.ok(generatedCode.includes('app.listen(PORT'))
      assert.ok(generatedCode.includes('Server running on port'))
    })

    it('should have an error event handler', () => {
      assert.ok(generatedCode.includes('app.on("error", (err, ctx)'))
      assert.ok(generatedCode.includes('ctx.status = err.status || 500'))
    })

    // Per-block-type structural verification
    for (const block of ast.blocks) {
      const blockName = (block as any).name || (block as any).target || (block as any).path || '?'
      const blockLabel = `${block.type} "${blockName}"`

      it(`should generate code for ${blockLabel}`, () => {
        switch (block.type) {
          case 'data': {
            const d = block as any
            assert.ok(generatedCode.includes(`export interface ${d.name}`), `Missing interface for data '${d.name}'`)
            assert.ok(generatedCode.includes(`const ${d.name.toLowerCase()}s:`), `Missing store for data '${d.name}'`)
            for (const f of d.fields) {
              assert.ok(generatedCode.includes(`  ${f.name}`), `Missing field '${f.name}' in data interface '${d.name}'`)
            }
            break
          }
          case 'rule': {
            const r = block as any
            assert.ok(generatedCode.includes(`function validate${r.name}(`), `Missing validate function 'validate${r.name}'`)
            break
          }
          case 'api': {
            const a = block as any
            if (a.protocol === 'REST') {
              assert.ok(generatedCode.includes(`// API: ${a.protocol} ${a.path || '/'}`), `Missing API comment for ${a.path}`)
              for (const route of a.routes) {
                assert.ok(
                  generatedCode.includes(`router.${route.method.toLowerCase()}(`),
                  `Missing route '${route.method} ${route.path}'`
                )
              }
            }
            break
          }
          case 'config': {
            const c = block as any
            assert.ok(c.name.length > 0, 'Config block should have a name')
            break
          }
        }
      })
    }
  })
}
