import { describe, it } from 'node:test'
import assert from 'node:assert/strict'
import fs from 'node:fs'
import path from 'node:path'
import { fileURLToPath } from 'node:url'
import { parse } from '../parser.js'
import { validate } from '../validator.js'
import { generateCode } from './index.js'

const __filename = fileURLToPath(import.meta.url)
const __dirname = path.dirname(__filename)

// Snapshots live in the source tree alongside the test, resolved from project root
const SNAPSHOT_DIR = path.resolve(process.cwd(), 'src/codegen/__snapshots__')
const EXAMPLES_DIR = path.resolve(process.cwd(), 'examples')

const UPDATE_SNAPSHOTS = process.env.UPDATE_SNAPSHOTS === '1'

function loadSnapshot(name: string): string | null {
  const filePath = path.join(SNAPSHOT_DIR, `${name}.snap`)
  try {
    return fs.readFileSync(filePath, 'utf-8')
  } catch {
    return null
  }
}

function saveSnapshot(name: string, code: string): void {
  if (!fs.existsSync(SNAPSHOT_DIR)) {
    fs.mkdirSync(SNAPSHOT_DIR, { recursive: true })
  }
  fs.writeFileSync(path.join(SNAPSHOT_DIR, `${name}.snap`), code, 'utf-8')
}

function camelCase(str: string): string {
  return str.charAt(0).toLowerCase() + str.slice(1)
}

// ---- Collect all example files ----
const exampleFiles = fs.readdirSync(EXAMPLES_DIR)
  .filter(f => f.endsWith('.clear'))
  .sort()

if (exampleFiles.length === 0) {
  throw new Error(`No .clear example files found in ${EXAMPLES_DIR}`)
}

// ---- One describe per example ----
for (const exampleFile of exampleFiles) {
  const snapshotName = exampleFile.replace(/\.clear$/, '')
  const filePath = path.join(EXAMPLES_DIR, exampleFile)
  const source = fs.readFileSync(filePath, 'utf-8')
  const parseResult = parse(source, exampleFile)
  const ast = parseResult.ast

  describe(`TypeScript codegen: ${exampleFile}`, () => {
    // 1. Parse succeeds
    it('should parse successfully', () => {
      assert.ok(ast !== null, `Parse failed: ${parseResult.errors.map(e => `${e.message} (${e.span.start.line}:${e.span.start.col})`).join('; ')}`)
    })

    // Skip remaining tests if parse failed
    if (ast === null) return

    const productName = ast.product.name

    // 2. Validation passes
    it('should validate successfully', () => {
      const validation = validate(ast)
      const errMsgs = validation.errors.map(e => `  ${e.message} (${e.span.start.line}:${e.span.start.col})`)
      assert.ok(validation.valid, `Validation failed for ${exampleFile}:\n${errMsgs.join('\n')}`)
    })

    // Generate code once for all tests
    const validation = validate(ast)
    const generatedCode = validation.valid
      ? generateCode(ast, { target: 'typescript' })
      : ''

    if (!validation.valid || !generatedCode) return

    // 3. Snapshot comparison
    it('should match stored snapshot', () => {
      if (UPDATE_SNAPSHOTS) {
        saveSnapshot(snapshotName, generatedCode)
        // When updating, we just save — don't compare
        return
      }

      const existing = loadSnapshot(snapshotName)
      if (existing === null) {
        // First run — create the snapshot and pass
        saveSnapshot(snapshotName, generatedCode)
        return
      }

      assert.strictEqual(generatedCode, existing)
    })

    // 4. Structural checks — verify generated code contains expected patterns
    it('should include auto-generated header', () => {
      assert.ok(generatedCode.includes('Auto-generated by Clear'))
      assert.ok(generatedCode.includes('Do not edit'))
      assert.ok(generatedCode.includes(`Source: ${productName}`))
    })

    it('should include a default export', () => {
      assert.ok(generatedCode.includes('export default'))
    })

    // 5. Per-block-type structural verification
    for (const block of ast.blocks) {
      const blockName = (block as any).name || (block as any).target || (block as any).path || '?'
      const blockLabel = `${block.type} "${blockName}"`

      it(`should generate code for ${blockLabel}`, () => {
        switch (block.type) {
          case 'data': {
            const d = block as any
            assert.ok(generatedCode.includes(`export interface ${d.name}`), `Missing interface for data '${d.name}'`)
            assert.ok(generatedCode.includes(`export function create${d.name}(`), `Missing create function for data '${d.name}'`)
            // Check each field appears in the interface
            for (const f of d.fields) {
              assert.ok(generatedCode.includes(`  ${f.name}`), `Missing field '${f.name}' in data interface '${d.name}'`)
            }
            break
          }
          case 'flow': {
            const f = block as any
            const funcName = camelCase(f.name)
            assert.ok(generatedCode.includes(`export async function ${funcName}(`), `Missing flow function '${funcName}'`)
            // Check each step appears
            for (const step of f.steps) {
              assert.ok(generatedCode.includes(`Step: ${step.name}`), `Missing step '${step.name}' in flow '${f.name}'`)
            }
            break
          }
          case 'rule': {
            const r = block as any
            assert.ok(generatedCode.includes(`export function apply${r.name}(`), `Missing rule function 'apply${r.name}'`)
            break
          }
          case 'screen': {
            const s = block as any
            assert.ok(generatedCode.includes(`export const ${s.name}Screen`), `Missing screen export '${s.name}Screen'`)
            if (s.sections && s.sections.length > 0) {
              assert.ok(generatedCode.includes('sections:'), `Missing sections in screen '${s.name}'`)
            }
            break
          }
          case 'agent': {
            const a = block as any
            assert.ok(generatedCode.includes(`export const ${a.name}`), `Missing agent export for '${a.name}'`)
            assert.ok(generatedCode.includes('handlers:'), `Missing handlers in agent '${a.name}'`)
            for (const h of a.handlers) {
              assert.ok(generatedCode.includes(`'${h.event}'`), `Missing handler for event '${h.event}' in agent '${a.name}'`)
            }
            break
          }
          case 'api': {
            const a = block as any
            if (a.protocol === 'REST') {
              const routeName = (a.path || '/').replace(/[^a-zA-Z0-9]/g, '_')
              assert.ok(
                generatedCode.includes(`register${a.protocol}Routes_${routeName}`),
                `Missing REST route registration for ${a.protocol} ${a.path}`
              )
              for (const route of a.routes) {
                assert.ok(
                  generatedCode.includes(route.method.toUpperCase()),
                  `Missing route method '${route.method}' for ${a.protocol} ${a.path}`
                )
              }
            } else if (a.protocol === 'MCP') {
              const mcpName = a.path && a.path !== '/' ? a.path.replace(/[^a-zA-Z0-9]/g, '_') : 'MCPServer'
              assert.ok(
                generatedCode.includes(`${mcpName}Tools`),
                `Missing MCP tools export for ${a.protocol} ${a.path}`
              )
              // Only tool routes are generated; resources and prompts are not
              const toolRoutes = a.routes.filter((r: any) => r.method === 'tool')
              for (const route of toolRoutes) {
                assert.ok(
                  generatedCode.includes(`${route.path}: {`),
                  `Missing MCP tool '${route.path}' for ${a.protocol} ${a.path}`
                )
              }
            }
            break
          }
          case 'event': {
            const e = block as any
            assert.ok(generatedCode.includes(`export function emit${e.name}(`), `Missing emit function for event '${e.name}'`)
            break
          }
          case 'config': {
            const c = block as any
            assert.ok(generatedCode.includes(`export const ${c.name}Config`), `Missing config export '${c.name}Config'`)
            break
          }
          case 'deploy': {
            assert.ok(generatedCode.includes('export const deployConfig'), 'Missing deployConfig export')
            assert.ok(generatedCode.includes(`target: '${(block as any).target}'`), `Missing deploy target '${(block as any).target}'`)
            break
          }
          case 'example': {
            const ex = block as any
            const safeName = ex.name.replace(/[^a-zA-Z0-9]/g, '_')
            assert.ok(generatedCode.includes(`export const example_${safeName}_`), `Missing example export for '${ex.name}'`)
            assert.ok(generatedCode.includes('description:'), `Missing description in example '${ex.name}'`)
            break
          }
          case 'skill': {
            const sk = block as any
            assert.ok(generatedCode.includes(`export class ${sk.name}`), `Missing skill class '${sk.name}'`)
            assert.ok(generatedCode.includes('static async execute('), `Missing execute method in skill '${sk.name}'`)
            break
          }
        }
      })
    }
  })
}
